#!/usr/bin/env python 
# -*- coding:utf-8 -*-

#在范围内寻找质数

#质数：除了1和它本身外，不再有其他的因数

'''
解题方法：使用了开根号法来判断是否为质数
开根号法：如果一个数是合数，那么有 a X b = N ,那么给N开根号后
一定有一个数是大于等于根号N，一个数小于等于根号N的
那么只需要小于等于根号N的那个数无法将N整除，就可以判断N为质数
'''

#导入math
import math
#输入用户需要检测的数字
lower_num = int(input("请输入您需要检测的数字的下限："))
upper_num = int(input("请输入您需要检测的数字的上限："))
count = 0
# 循环判断是否能够被整除
for num in range(lower_num, upper_num + 1):
    #质数大于1
    if num >1:
        # 找到小于num平方根的那个数
        Sign_min = math.floor(num ** 0.5)

        for i in range(2,Sign_min + 2): #这里需要注意，调试过程中2和3开方后结果是为1的，+1后范围为[2,2]，无法输出结果
            #判断是否为质数
            if num % i == 0:
                print("这个数字不是质数！",num)
                break
            else:
                print("是质数",num)
                break
    else:
        print('既不是质数，也不是非质数',num)
