#!/usr/bin/env python 
# -*- coding:utf-8 -*-

#求 字符在字符串中出现的次数
a = input('请输入一个字符串: ')
b = input('请输入一个字串：')

def ch(Str,Wor):
    j=0     #初始数据类型为整形
    i=''    #初始数据类型为字符型
    for i in Str:
        if i == Wor:
            j += 1
    print(i, '出现了{}次'.format(j))


ch(a,b)
