#!/usr/bin/env python 
# -*- coding:utf-8 -*-

#最小公倍数
'''找到两个数中最大的那个，然后循环
找到能够被两个数整除的那个数
'''

def commom(num1,num2):
    if num1 > num2 :
        temp = num1
    else:
        temp = num2
    while 1:
        if (temp % num1 == 0) and (temp % num2 == 0):
            return temp
        else:
            temp += 1
num1 = int(input('请输入第一个数：'))
num2 = int(input('请输入第二个数：'))
print(commom(num1,num2))
