#!/usr/bin/env python 
# -*- coding:utf-8 -*-

#最大公约数算法
'''
分析：求最大公约数，要以最小的那个数为界限
然后找出能够整除num1 和 num2 的那个数
再找到其中最大的那个
'''

num1 = int(input('请输入第一个数：'))
num2 = int(input('请输入第二个数：'))

def common(num1,num2):
    if num1 > num2:
        temp = num2
    else:
        temp = num1
        for i in range(1,temp + 1):
            if(num1 % i == 0) and (num2 % i == 0):
                a = i
    return a

print(common(num1,num2))

