#!/usr/bin/env python 
# -*- coding:utf-8 -*-

#阿姆斯特朗数
#获取一定区间内的阿姆斯特朗数

lower = int(input('请输入一个下限值：'))
upper = int(input('请输入一个上限值：'))


def amustelon(lower,upper):
    #初始化和
    sum = 0
    #遍历范围所有的值
    for num in range(lower,upper):
    #提取n的长度
        n = len(str(num))
        #将数字的每一位都提取出来
        for a in str(num):
            #每一位的数字 ** 数字的位数 + 下一位得到的结果
           sum = sum + int(a) ** n
        #判断是否相等
        if sum == num:
            print(num,end=" ")
        #清零
        sum =0
amustelon(lower,upper)
